"""baseline — squash of every hand-rolled migrate_*() into one clean starting point

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-01

This is the CURRENT end-state schema: every table exactly as it exists today, AFTER
every `migrate_*()` in webapp/db.py has run (annotation.stroke_width + outline_json,
annotation_set.created_by_user_id, project(_annotator/_image) in their final shape,
meta, …). See docs/plans/Plan — Adopt Alembic (baseline + forward migrations).md.

Hand-written, NOT autogenerated — this must equal today's real schema exactly so an
existing prod/dev DB can be `alembic stamp`-ed onto this revision (see webapp/db.py's
auto_create_schema()) without upgrade() ever running against it. upgrade() only
actually executes for a genuinely fresh DB (no tables yet).

The old migrate_*() function BODIES stay in webapp/db.py as the source-of-truth this
was transcribed from, but are no longer called from the startup path — this revision
is now the one place that builds the schema from nothing.
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Table creation order matters (FK targets must exist first) — mirrors webapp/db.py's
# _DDL ordering exactly, with the migrate_*() column additions folded in place:
#   annotation_set  + created_by_user_id  (migrate_add_user_fk)
#   annotation      + stroke_width        (migrate_annotation_stroke_width)
#                   + outline_json        (migrate_annotation_outline)
# project / project_annotator / project_image / project.tiling_confirmed were already
# folded into _DDL itself (migrate_project_annotator_user_fk / _source_path /
# _tiling_confirmed are now no-ops on a fresh DB; their bodies remain for old DBs that
# pre-date this baseline being stamped, but no such DB should exist after stamping).
_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      username TEXT UNIQUE NOT NULL,
      password_hash TEXT,
      created_at REAL NOT NULL DEFAULT (unixepoch())
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS invite_codes (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      token TEXT UNIQUE NOT NULL,
      expires REAL NOT NULL,
      created_at REAL NOT NULL DEFAULT (unixepoch())
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS settings (
      key TEXT PRIMARY KEY, value TEXT, updated_at REAL NOT NULL DEFAULT (unixepoch())
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS annotation_set (
      id           TEXT PRIMARY KEY,
      display_name TEXT NOT NULL,
      image_hash   TEXT NOT NULL,
      image_ext    TEXT NOT NULL,
      kind         TEXT NOT NULL CHECK (kind IN ('raw','merged','reannotated')),
      provenance   TEXT,
      created_by   TEXT,
      created_at   TEXT NOT NULL,
      terminal     INTEGER NOT NULL DEFAULT 0,
      created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_annotation_set_image_hash ON annotation_set (image_hash)",
    """
    CREATE TABLE IF NOT EXISTS merge (
      id          TEXT PRIMARY KEY,
      set_id      TEXT REFERENCES annotation_set(id),
      image_hash  TEXT NOT NULL,
      doc         TEXT NOT NULL,
      created_by  TEXT,
      updated_at  TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_merge_set_id ON merge (set_id)",
    """
    CREATE TABLE IF NOT EXISTS reannot_session (
      id            TEXT PRIMARY KEY,
      merge_id      TEXT NOT NULL REFERENCES merge(id),
      image_hash    TEXT NOT NULL,
      status        TEXT NOT NULL DEFAULT 'active'
                      CHECK (status IN ('active','complete')),
      planned_order TEXT NOT NULL,
      active_pile   TEXT,
      result_set_id TEXT REFERENCES annotation_set(id),
      created_by    TEXT,
      created_at    TEXT NOT NULL,
      completed_at  TEXT
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_reannot_session_merge_id ON reannot_session (merge_id)",
    """
    CREATE TABLE IF NOT EXISTS reannot_pile (
      id             TEXT PRIMARY KEY,
      session_id     TEXT NOT NULL REFERENCES reannot_session(id),
      source_pile_id TEXT,
      order_index    INTEGER NOT NULL,
      bbox           TEXT NOT NULL,
      status         TEXT NOT NULL DEFAULT 'pending'
                       CHECK (status IN ('pending','done')),
      resolved_count INTEGER
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_reannot_pile_session_id ON reannot_pile (session_id)",
    """
    CREATE TABLE IF NOT EXISTS reannot_generation (
      id         TEXT PRIMARY KEY,
      pile_id    TEXT NOT NULL REFERENCES reannot_pile(id),
      gen_index  INTEGER NOT NULL,
      created_at TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_reannot_generation_pile_id ON reannot_generation (pile_id)",
    """
    CREATE TABLE IF NOT EXISTS reannot_polygon (
      id            TEXT PRIMARY KEY,
      generation_id TEXT NOT NULL REFERENCES reannot_generation(id),
      participant   TEXT NOT NULL,
      points        TEXT NOT NULL,
      bbox          TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_reannot_polygon_generation_id ON reannot_polygon (generation_id)",
    """
    CREATE TABLE IF NOT EXISTS project (
      id               TEXT PRIMARY KEY,
      name             TEXT NOT NULL,
      tile_size_px     INTEGER NOT NULL DEFAULT 128,
      black_threshold  INTEGER NOT NULL DEFAULT 0,
      classes_json     TEXT NOT NULL DEFAULT '[]',
      tiling_confirmed INTEGER NOT NULL DEFAULT 0,
      created_by       TEXT,
      created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
      created_at       TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS project_annotator (
      id         TEXT PRIMARY KEY,
      project_id TEXT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
      user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      byline     TEXT NOT NULL,
      UNIQUE (project_id, user_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS project_image (
      id          TEXT PRIMARY KEY,
      project_id  TEXT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
      image_hash  TEXT NOT NULL,
      image_ext   TEXT NOT NULL,
      source_name TEXT,
      source_path TEXT,
      width       INTEGER,
      height      INTEGER,
      origin_y    INTEGER NOT NULL DEFAULT 0,
      leaf_x INTEGER, leaf_y INTEGER, leaf_w INTEGER, leaf_h INTEGER,
      created_at  TEXT NOT NULL,
      UNIQUE (project_id, image_hash)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_project_image_project ON project_image (project_id)",
    """
    CREATE TABLE IF NOT EXISTS tile (
      id               TEXT PRIMARY KEY,
      project_image_id TEXT NOT NULL REFERENCES project_image(id) ON DELETE CASCADE,
      x INTEGER NOT NULL, y INTEGER NOT NULL, w INTEGER NOT NULL, h INTEGER NOT NULL,
      UNIQUE (project_image_id, x, y)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS batch (
      id         TEXT PRIMARY KEY,
      project_id TEXT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
      seq        INTEGER NOT NULL,
      size       INTEGER NOT NULL DEFAULT 5,
      status     TEXT NOT NULL DEFAULT 'annotation_in_progress',
      created_at TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_batch_project ON batch (project_id)",
    """
    CREATE TABLE IF NOT EXISTS batch_tile (
      id       TEXT PRIMARY KEY,
      batch_id TEXT NOT NULL REFERENCES batch(id) ON DELETE CASCADE,
      tile_id  TEXT NOT NULL REFERENCES tile(id) ON DELETE CASCADE,
      UNIQUE (batch_id, tile_id)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_batch_tile_batch ON batch_tile (batch_id)",
    """
    CREATE TABLE IF NOT EXISTS annotator_tile (
      id            TEXT PRIMARY KEY,
      batch_tile_id TEXT NOT NULL REFERENCES batch_tile(id) ON DELETE CASCADE,
      annotator     TEXT NOT NULL,
      state         TEXT NOT NULL DEFAULT 'assigned',
      updated_at    TEXT,
      UNIQUE (batch_tile_id, annotator)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_annotator_tile_bt ON annotator_tile (batch_tile_id)",
    """
    CREATE TABLE IF NOT EXISTS annotation (
      id            TEXT PRIMARY KEY,
      project_id    TEXT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
      project_image_id TEXT REFERENCES project_image(id) ON DELETE CASCADE,
      annotator     TEXT NOT NULL,
      kind          TEXT NOT NULL,
      pass_no       INTEGER,
      points_json   TEXT NOT NULL,
      label         TEXT,
      viewport_json TEXT,
      hsv_hist_json TEXT,
      created_at    TEXT NOT NULL,
      updated_at    TEXT NOT NULL,
      deleted_at    TEXT,
      stroke_width  REAL,
      outline_json  TEXT
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_annotation_project ON annotation (project_id, annotator)",
    """
    CREATE TABLE IF NOT EXISTS annotation_tile (
      annotation_id TEXT NOT NULL REFERENCES annotation(id) ON DELETE CASCADE,
      tile_id       TEXT NOT NULL REFERENCES tile(id) ON DELETE CASCADE,
      PRIMARY KEY (annotation_id, tile_id)
    )
    """,
    # `meta` key/value table (webapp/db.py's migrate_meta) — schema only; app_version is
    # written at boot, not baked in here.
    "CREATE TABLE IF NOT EXISTS meta (key TEXT PRIMARY KEY, value TEXT)",
]

# Reverse-dependency order for a clean downgrade.
_DROP_ORDER = [
    'meta',
    'annotation_tile',
    'annotation',
    'annotator_tile',
    'batch_tile',
    'batch',
    'tile',
    'project_image',
    'project_annotator',
    'project',
    'reannot_polygon',
    'reannot_generation',
    'reannot_pile',
    'reannot_session',
    'merge',
    'annotation_set',
    'settings',
    'invite_codes',
    'users',
]


def upgrade() -> None:
    for stmt in _STATEMENTS:
        op.execute(stmt)


def downgrade() -> None:
    for table in _DROP_ORDER:
        op.execute(f'DROP TABLE IF EXISTS {table}')
